project:
  type: website

website:
  title: "Jason H. Nicholson"
  site-url: "https://jasonhnicholson.com"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - blog.qmd
      - text: Pages
        menu:
          - pages/numerical-methods/index.qmd
          - pages/system-identification/index.qmd
      - about.qmd
      
          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

engines: ['julia']

