project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Jason H. Nicholson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Pages
        menu:
        - text: Numerical Methods
          href: pages/numerical-methods/index.qmd
        - text: System Identification
          href: pages/system-identification/index.qmd
          

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

engines: ['julia']

