project:
  type: website
  output-dir: __site
website:
  title: "Jason H. Nicholson"
format:
  html:
    theme: default
    include-in-header: _includes/head.html
    include-after-body: _includes/footer.html
    code-copy: true
    highlight-style: pygments
    toc: true
quiet: true
engines: ['julia']